### ISSUE TITLE
Make it work with SSR

### ISSUE THREAD

**Issue by lupas** [lupas/nuxt-fire-vuexfire-example#1]
Make it work with SSR

**Comment by lupas** [comment]
Might be able to initialize vuexfire within fetch(), 
there some discussion here https://github.com/vuejs/vuefire/issues/203#issuecomment-510683266 that might help.

**Comment by CoolONEOfficial** [comment]
I was able to solve the problem like this:

_pages/index.vue_

```ts
import {
  Action,
  Component,
  Getter,
  Mutation,
  Vue
} from 'nuxt-property-decorator'

@Component({})
export default class extends Vue {
  @Getter
  count

  @Mutation
  updateCount

  @Action
  setCountCollectionRef

  created() {
    const ref = this.$fireStore
      .collection('countCollection')
      .doc('countDocument')
    this.setCountCollectionRef(ref)
  }

  fetch(ctx) {
    return ctx.app.$fireStore
      .collection('countCollection')
      .doc('countDocument')
      .get()
      .then(function(doc) {
        if (doc.exists) {
          console.log('Document data:', doc.data())
          ctx.store.commit('updateCount', doc.data().count)
        } else {
          console.log('No such document!')
        }
      })
      .catch(function(error) {
        console.log('Error getting document:', error)
      })
  }
}
```

_store/index.ts_
```
import { vuexfireMutations, firestoreAction } from 'vuexfire'
export const state = () => ({
  countDocument: {
    count: 'loading'
  }
})
export const mutations = {
  ...vuexfireMutations,
  updateCount(state, count) {
    state.countDocument.count = count
  }
}
export const actions = {
  setCountCollectionRef: firestoreAction(function(context, ref) {
    context.bindFirestoreRef('countDocument', ref)
  })
}
export const getters = {
  count(state) {
    return state.countDocument.count
  }
}
```

**Comment by lupas** [comment]
> I was able to solve the problem like this:

Thanks for the contribution!

This works well in SSR mode indeed, however it kind of defeats the benefits of not having to write your own getters and mutations for Firestore. And if there is a lot of data to be bound to from Firestore, not just a simple count, it might quickly get verbose again.

I added it as a workaround for now, but the goal would still be to find a way to implement Vue(x)fire without such a manual workaround :)

**Comment by lupas** [comment]
@CoolONEOfficial 

Finally found a way to add the bindings on server side without the need of writing mutations:

```js
export const actions = {
  // Make the function async
  bindCountDocument: firestoreAction(async function({ bindFirestoreRef }) {
    const ref = this.$fireStore
      .collection('countCollection')
      .doc('countDocument')
    // AWAIT and the wait: true options are important
    await bindFirestoreRef('countDocument', ref, { wait: true })
  })
}
```

And then you just bind once in "fetch" (for server side) and once e.g. in "mounted" (for client side).

I already updated the example.

Now the only thing that's missing is:
- [ ] Find a way to do the bindings without having to write it twice (in fetch AND mounted)

Let me know if that solutions works for you!
