### ISSUE TITLE
broken with new version of packages - Cannot read property 'collection' of undefined

### ISSUE THREAD

**Issue by msreekm** [lupas/nuxt-fire-vuexfire-example#11]
this is my package.json 
 "@nuxtjs/firebase": "^7.3.0",
    "core-js": "^2.6.11",
    "firebase": "^8.2.1",
    "nuxt": "^2.12.2",
    "vuexfire": "^3.2.5"

getting this error- 
Cannot read property 'collection' of undefined

**Comment by msreekm** [comment]
@lupas -created a PR [here](https://github.com/lupas/nuxt-fire-vuexfire-example/pull/12/files).

**Comment by lupas** [comment]
Thanks - just merged. :) Appreciate it!
