### ISSUE TITLE
Implement Authentication

### ISSUE THREAD

**Issue by mauriziocalarese** [lupas/nuxt-fire-vuexfire-example#9]
Hi,

first of all, compliments for the great work :)

I'm trying to implement the authentication with it, in a spa, storing data in the vuex store.

I have many doubts about best practices, and I'm also worried about multiple reading operations.

Could you please add how you would use the module to authenticate the user, storing his information within the store?

Again, thanks a lot :)

**Comment by SKFrozenCloud** [comment]
You should be able to access the user just by calling the native API.

https://firebase.nuxtjs.org/service-options/auth

**Comment by lupas** [comment]
Hey there.

I would advise you to set up an onAuthStateChanged mutation (or action) as described in the [Docs](https://firebase.nuxtjs.org/service-options/auth/#onauthstatechangedmutation) and then just update the user in the store through that mutation or action.

You can follow the code in the [nuxt-fire-demo](https://github.com/lupas/nuxt-firebase-demo) on how to do basic authentication.

br, Pascal
